
GET https://restapi.test HTTP/1.1

### Call a user

GET https://restapi.test/user/6 HTTP/1.1

### Add User
POST http://restapi.test/adduser HTTP/1.1
Content-Type: application/json

{ 
    "name": "Marcos Rios",
    "email": "marcosrios@gmail.com",
    "doc": "30.588.144",
    "gener": "F"
}

### Edit user
POST http://restapi.test/edituser HTTP/1.1
Content-Type: application/json

{ 
    "id": "5",
    "name": "Roxana Sanders",
    "email": "roxana@gmail.com",
    "doc": "44.788.144",
    "gener": "F"
}

### Delete user
GET http://localhost/restapi/deluser/6 HTTP/1.1

### test aparte
POST https://api.mercadopago.com/users/test_user
Content-Type: application/json
Authorization: qsUZ9sH1F4dqUAmCQXXzNklKbhypHFxB

{"site_id":"ARG"}